### ISSUE TITLE
Question: Which license do we need for this repository?

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/OpenPedCan-api#10]
Currently, there is no license attached to this repository. Which license do we need?

Here is the link to OpenPedCan-analysis license, <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/LICENSE.md>.

**Comment by logstar** [comment]
@taylordm @chinwallaa - I was wondeirng if we could use _Creative Commons Attribution 4.0 International_ (CC-BY-4.0) license, which is the same license as the [OpenPBTA](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/80d6e355ac35e11ff5ed8d4e25b7eb45d9720113/LICENSE.md)/[OpenPedCan-analysis](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/ed03c60a21de63291163ed3f7c8a05e83c323d81/LICENSE.md).

The CC-BY-4.0 license permits use/distribution/modification and requires attribution to the licensed material.

However, CC-BY-4.0 license does not permit patent use. I was wondering if the plots and tables in the API need to allow patent use for drug development.

Following is a summary from <https://choosealicense.com/licenses/cc-by-4.0/>:

<img width="800" alt="cc-by-4 0" src="https://user-images.githubusercontent.com/9595639/157490605-7e93ed70-b313-4622-a9d8-be1e81ae3bc5.png">

Following is the link to a table of various licenses, <https://choosealicense.com/appendix/>, which is useful for choosing one.

I have also reviewed the following licenses:

- [_GNU General Public License v3.0_](https://choosealicense.com/licenses/gpl-3.0/). This license does not require attribution to the licensed material.
- [_Open Data Commons Open Database License v1.0_](https://choosealicense.com/licenses/odbl-1.0/). This license does not cover the contents, e.g., plots and tables, in the database. This license also does not require attribution to the licensed material or permit patent use.
- [_MIT License_](https://choosealicense.com/licenses/mit/). This license does not require attribution to the licensed material.

Let me know if you have questions or suggestions.

**Comment by chinwallaa** [comment]
we can check with FNL, but my vote is on the creative commons license.   

>>However, CC-BY-4.0 license does not permit patent use. I was wondering if the plots and tables in the API need to allow patent use for drug development.

The licenses are for use of the software - code/workflow and not the data.   Data would be governed by an DUA if needed, MTP intent is for drug development :)

**Comment by jharenza** [comment]
Hi @logstar - we can go with CC-BY-4.0.

**Comment by jharenza** [comment]
CC-BY-4.0 is our current license, so will close
