### ISSUE TITLE
Enable the Cross-Origin Resource Sharing (CORS) on the server side

### ISSUE THREAD

**Issue by jonkiky** [PediatricOpenTargets/OpenPedCan-api#24]
Can you help us to  enable the Cross-Origin Resource Sharing (CORS) on the server side?

By default, the API endpoint from rplumber forbids “cross-domain” requests. if you can add codes below to enable the cors thatwill great help us.
```
#* @filter cors
cors <- function(res) {
    res$setHeader("Access-Control-Allow-Origin", "*")
    plumber::forward()
}
```
refers: https://www.rplumber.io/articles/security.html 

The request from OT to R will be cross-domain request. If server-side not allow the cross-domain request, we have to find something workaround which is not a good practice in general. @blackdenc

**Comment by logstar** [comment]
R plumber documentation also states that enabling CORS may cause security issues.

> Understand that, this is a temporary workaround and can constitute critical security issues if some endpoints that shouldn’t be exposed through CORS and have been enabled by default.

Ref: <https://www.rplumber.io/articles/security.html#cross-origin-resource-sharing-cors>

@jonkiky Thank you for creating this issue.

I wonder if you could briefly explain your use cases of CORS and the expected behaviors CORS enabled and disabled. This would be helpful for us to evaluate the benefits and potential security issues of enabling CORS.

We also had conversations on restricting API connection to PedOT IP addresses. Would enabling CROS make the IP address restriction infeasible?

cc @chinwallaa @blackdenc

**Comment by blackdenc** [comment]
I think this should be ok since the data is public anyways, and I agree with @jonkiky that restricting IP ranges is a good thing to do. Do we know what CIDR range FNL is going to call this API from?

**Comment by logstar** [comment]
@jonkiky @blackdenc - Thank you for the replies. I agree. The API server can enable CORS, because all endpoints are providing public data, and none of the endpoints can alter any server data.

I will add the plumber CORS filter in <https://github.com/PediatricOpenTargets/OpenPedCan-api/pull/20>.

@blackdenc @jonkiky - Could we only restrict IP address on the production server? All IP accesses to DEV and QA servers would be helpful for anyone who want to review the API server responses.

**Comment by blackdenc** [comment]
@logstar, yes, we can control the allowed CIDR range of IPs for the QA environment by changing this parameter, and leaving the other alone will allow us to keep the DEV environment open.
https://github.com/PediatricOpenTargets/OpenPedCan-api/blob/7dce7375211d148a666adcbdfd79c95e2f477ebf/Jenkinsfile#L12

**Comment by logstar** [comment]
> @logstar, yes, we can control the allowed CIDR range of IPs for the QA environment by changing this parameter, and leaving the other alone will allow us to keep the DEV environment open.
> https://github.com/PediatricOpenTargets/OpenPedCan-api/blob/7dce7375211d148a666adcbdfd79c95e2f477ebf/Jenkinsfile#L12

@blackdenc Thank you for the pointer. I think we only need to change `prd_cidr` to restrict to PedOT IPs. The all open `qa_cidr` and `dev_cidr` are helpful for people to review the API endpoint results.

<https://github.com/PediatricOpenTargets/OpenPedCan-api/blob/7dce7375211d148a666adcbdfd79c95e2f477ebf/Jenkinsfile#L11>

@jonkiky Could you provide a list of PedOT instance IP address to us, either at this issue or through Slack?

**Comment by jonkiky** [comment]
Here are the IPs of dev, qa and stage site of PedOT.
dev: https://ppdc-otp-dev.bento-tools.org/  ->52.2.138.24
qa: https://ppdc-otp-qa.bento-tools.org/->54.174.248.68
stage: https://ppdc-otp-stage.bento-tools.org/->52.1.43.50


@blackdenc  @logstar

**Comment by logstar** [comment]
> Here are the IPs of dev, qa and stage site of PedOT.
> dev: https://ppdc-otp-dev.bento-tools.org/ -> 52.2.138.24
> qa: https://ppdc-otp-qa.bento-tools.org/ -> 54.174.248.68
> stage: https://ppdc-otp-stage.bento-tools.org/ -> 52.1.43.50
> 
> @blackdenc @logstar

Thank you for the reply.

@blackdenc Could you make changes in #20 to restrict `prd_cidr` to PedOT instance IP addresses?

**Comment by logstar** [comment]
@jonkiky CORS is enabled in this commit, <https://github.com/PediatricOpenTargets/OpenPedCan-api/pull/20/commits/82af41605573f4c2a318abcdb22b174fdfa48a4d>. The `cors` filter works as expected locally, and will be deployed on the development server, <https://openpedcan-api-dev.d3b.io/__docs__/>, soon. Once #20 is merged to main, the changes will be deployed on the QA server, <https://openpedcan-api-qa.d3b.io/__docs__/>.

```text
$ curl -v http://localhost:8082/tpm/gene-all-cancer/json?ensemblId=ENSG00000273032
*   Trying 127.0.0.1:8082...
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET /tpm/gene-all-cancer/json?ensemblId=ENSG00000273032 HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.78.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Thu, 09 Sep 2021 17:57:13 GMT
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Content-Length: 15308
< 
[{"x_labels":"Acute Lymphoblastic Leukemia (Dataset = TARGET, N = 458)"...
```

**Comment by jonkiky** [comment]
> @jonkiky CORS is enabled in this commit, [82af416](https://github.com/PediatricOpenTargets/OpenPedCan-api/commit/82af41605573f4c2a318abcdb22b174fdfa48a4d). The `cors` filter works as expected locally, and will be deployed on the development server, https://openpedcan-api-dev.d3b.io/__docs__/, soon. Once #20 is merged to main, the changes will be deployed on the QA server, https://openpedcan-api-qa.d3b.io/__docs__/.
> 
> ```
> $ curl -v http://localhost:8082/tpm/gene-all-cancer/json?ensemblId=ENSG00000273032
> *   Trying 127.0.0.1:8082...
> * Connected to localhost (127.0.0.1) port 8082 (#0)
> > GET /tpm/gene-all-cancer/json?ensemblId=ENSG00000273032 HTTP/1.1
> > Host: localhost:8082
> > User-Agent: curl/7.78.0
> > Accept: */*
> > 
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 200 OK
> < Date: Thu, 09 Sep 2021 17:57:13 GMT
> < Access-Control-Allow-Origin: *
> < Content-Type: application/json
> < Content-Length: 15308
> < 
> [{"x_labels":"Acute Lymphoblastic Leukemia (Dataset = TARGET, N = 458)"...
> ```

Thank you !

**Comment by logstar** [comment]
@jonkiky You're welcome! CORS is enabled on the development server. Could you test the development server on PedOT and let us know if it works as expected?

```text
$ curl -v https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/json?ensemblId=ENSG00000273032
*   Trying 34.234.177.218:443...
* Connected to openpedcan-api-dev.d3b.io (34.234.177.218) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /home/ubuntu/miniconda3/ssl/cacert.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.d3b.io
*  start date: Aug 20 00:00:00 2021 GMT
*  expire date: Sep 18 23:59:59 2022 GMT
*  subjectAltName: host "openpedcan-api-dev.d3b.io" matched cert's "*.d3b.io"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5646aa0f0fc0)
> GET /tpm/gene-all-cancer/json?ensemblId=ENSG00000273032 HTTP/2
> Host: openpedcan-api-dev.d3b.io
> user-agent: curl/7.78.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
< date: Thu, 09 Sep 2021 18:39:44 GMT
< content-type: application/json
< content-length: 15308
< access-control-allow-origin: *
<
[{"x_labels":"Acute Lymphoblastic Leukemia (Dataset = TARGET, N = 458)"...
```

**Comment by jonkiky** [comment]
> @jonkiky You're welcome! CORS is enabled on the development server. Could you test the development server on PedOT and let us know if it works as expected?
> 
> ```
> $ curl -v https://openpedcan-api-dev.d3b.io/tpm/gene-all-cancer/json?ensemblId=ENSG00000273032
> *   Trying 34.234.177.218:443...
> * Connected to openpedcan-api-dev.d3b.io (34.234.177.218) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *  CAfile: /home/ubuntu/miniconda3/ssl/cacert.pem
> *  CApath: none
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
> * ALPN, server accepted to use h2
> * Server certificate:
> *  subject: CN=*.d3b.io
> *  start date: Aug 20 00:00:00 2021 GMT
> *  expire date: Sep 18 23:59:59 2022 GMT
> *  subjectAltName: host "openpedcan-api-dev.d3b.io" matched cert's "*.d3b.io"
> *  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
> *  SSL certificate verify ok.
> * Using HTTP2, server supports multiplexing
> * Connection state changed (HTTP/2 confirmed)
> * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> * Using Stream ID: 1 (easy handle 0x5646aa0f0fc0)
> > GET /tpm/gene-all-cancer/json?ensemblId=ENSG00000273032 HTTP/2
> > Host: openpedcan-api-dev.d3b.io
> > user-agent: curl/7.78.0
> > accept: */*
> >
> * Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
> < HTTP/2 200
> < date: Thu, 09 Sep 2021 18:39:44 GMT
> < content-type: application/json
> < content-length: 15308
> < access-control-allow-origin: *
> <
> [{"x_labels":"Acute Lymphoblastic Leukemia (Dataset = TARGET, N = 458)"...
> ```

Thanks bunches! It works as expected.  Will looking forward to test it out in the Prod.   @logstar @blackdenc

**Comment by logstar** [comment]
@jonkiky - I was wondering if we could close this issue.

I was also wondering if we still need to limit API dev/qa/prd server access to only MTP website IP addresses listed in <https://github.com/PediatricOpenTargets/OpenPedCan-api/issues/24#issuecomment-916253817>. Limit the access would block reviewers and developers from directly evaluating and testing the API dev/qa/prd servers. For security and performance concerns, I think they could be resolved by running the API server and MTP website servers within the same local network as planned previously.

cc @taylordm @chinwallaa @blackdenc

**Comment by jonkiky** [comment]
> @jonkiky - I was wondering if we could close this issue.
> 
> I was also wondering if we still need to limit API dev/qa/prd server access to only MTP website IP addresses listed in [#24 (comment)](https://github.com/PediatricOpenTargets/OpenPedCan-api/issues/24#issuecomment-916253817). Limit the access would block reviewers and developers from directly evaluating and testing the API dev/qa/prd servers. For security and performance concerns, I think they could be resolved by running the API server and MTP website servers within the same local network as planned previously.
> 
> cc @taylordm @chinwallaa @blackdenc

@logstar    It looks good to me, well resolved and can be closed. Thank you.

**Comment by logstar** [comment]
@jonkiky Thank you for the reply. I will close this issue.

It is good to know that IP access limit is not a block for you. After the MTP server migration, we could further discuss whether the API IP access limit would be necessary or not.
