### ISSUE TITLE
Got Errors when running the shiny-app code

### ISSUE THREAD

**Issue by jonkiky** [PediatricOpenTargets/OpenPedCan-api#3]
What I did is,  I used the analysis repo to download the input data files, then used R studio to open the project. Under server.R. Simply clicked run app button.  Then play around the app . After I clicked create box plot. the program throw me the errors show below. 

<img width="791" alt="Screen Shot 2021-08-23 at 11 43 37 AM" src="https://user-images.githubusercontent.com/6140388/130476801-60ae9f0d-685a-4b8b-b22e-be77c50eb1f9.png">

    
    Here is my project's file  strucuture.  R version 4.1.0 
<img width="802" alt="Screen Shot 2021-08-23 at 11 14 03 AM" src="https://user-images.githubusercontent.com/6140388/130476034-a39d538e-cdea-41f9-bc66-ff557c675dc8.png">

**Comment by komalsrathi** [comment]
@jonkiky can you pull the code and run again? I fixed an issue which was pulling DNA samples. cc: @jharenza

**Comment by komalsrathi** [comment]
Also, there is an [issue](https://github.com/PediatricOpenTargets/ticket-tracker/issues/181) with the EFO/Mondo mapping file so you won't get output tables for the following types:

"Acute Lymphoblastic Leukemia" 
"Acute Myeloid Leukemia"      
"Chordoma"

**Comment by jonkiky** [comment]
@komalsrathi  It is working now. Thanks.
