### ISSUE TITLE
Create QA database RDS instance

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/OpenPedCan-api#39]
The DEV and QA API HTTP servers need separate database RDS instances, because testing new tables in #37 and [new OpenPedCan-analysis data releases](https://github.com/PediatricOpenTargets/ticket-tracker/issues/188) requires dropping existing tables first.

@blackdenc will create the QA RDS instance. I will load data into the instance.

cc @taylordm @afarrel @chinwallaa

**Comment by blackdenc** [comment]
This is done
