### ISSUE TITLE
Change boxplot box fill colors to be color blind friendly

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/OpenPedCan-api#54]
Replace boxplot box fill colors from red to blue to be color blind friendly, as suggested by @taylordm .

Current box fill colors:

<img width="458" alt="Screen Shot 2021-11-12 at 2 37 43 PM" src="https://user-images.githubusercontent.com/9595639/141525034-3f5fcf16-7bcd-46c6-a71b-d16626a86d40.png">

Proposed replacement box fill colors:

<img width="512" alt="Screen Shot 2021-11-12 at 2 41 15 PM" src="https://user-images.githubusercontent.com/9595639/141525433-697e8356-449e-41fb-95f2-27b1f7efeef5.png">

cc @chinwallaa @afarrel

**Comment by logstar** [comment]
@taylordm @chinwallaa - Following are two example plots:

![plot1](https://user-images.githubusercontent.com/9595639/141527667-db635015-ccce-445c-997d-a1ff6ea497e4.png)

![plot2](https://user-images.githubusercontent.com/9595639/141527684-9ae6f06c-960e-43ae-9801-b402d3bf11a6.png)

**Comment by jharenza** [comment]
@logstar can we use two different colors here for primary and relapse from [here](https://stackoverflow.com/questions/57153428/r-plot-color-combinations-that-are-colorblind-accessible) to make them stand out more? Maybe `#56B4E9` or `#0072B2` for primary and `#CC79A7` for relapse?

If we go with two shades of the same color, are those divergent enough? May have to use `#56B4E9` and `#0072B2`?

**Comment by logstar** [comment]
> @logstar can we use two different colors here for primary and relapse from [here](https://stackoverflow.com/questions/57153428/r-plot-color-combinations-that-are-colorblind-accessible) to make them stand out more? Maybe `#56B4E9` or `#0072B2` for primary and `#CC79A7` for relapse?
> 
> If we go with two shades of the same color, are those divergent enough? May have to use `#56B4E9` and `#0072B2`?

@jharenza Thank you for the suggestion. We could use two different colors.

@taylordm I was wondering if you have any preference.

**Comment by logstar** [comment]
Following are example plots using colors suggested by @jharenza:

![plot3](https://user-images.githubusercontent.com/9595639/141529287-8817e084-44cf-4a14-8a26-46fdddb8d4b9.png)

![plot4](https://user-images.githubusercontent.com/9595639/141529441-0c88c8e5-3d42-4f05-bf7c-82d52166823d.png)

**Comment by logstar** [comment]
@taylordm @jharenza - I will use blue and orange for primary and relapse tumors respectively. Following is an example plot:

![plot3](https://user-images.githubusercontent.com/9595639/141850672-dbae4a29-cf33-45d6-be3e-341e5ce179e6.png)

**Comment by logstar** [comment]
According to @taylordm's suggestion in the meeting, I will change the color for primary and relapse tumors from blue to purple `#332288`. The purple color is from the `Safe` palette in <https://stackoverflow.com/a/57157075/4638182>.

<img width="96" alt="Screen Shot 2021-11-17 at 8 14 16 AM" src="https://user-images.githubusercontent.com/9595639/142207470-3fcb4fbd-e7ea-4340-aa76-145e12a27e4f.png">

**Comment by logstar** [comment]
`#332288` purple is too dark to see box median clearly, so I will use `#A997DF` purple instead. The `#A997DF` purple is from the "Palette 2" in <https://medium.com/cafe-pixo/inclusive-color-palettes-for-the-web-bbfe8cf2410e>.

**`#332288` purple**

![plot](https://user-images.githubusercontent.com/9595639/142212834-6a12d1bb-1109-4af5-8abe-dba73ab2ed41.png)

**`#A997DF` purple**

![plot2](https://user-images.githubusercontent.com/9595639/142212903-f2afa5b4-5860-4fbd-9c7c-0e6161dae68f.png)
