### ISSUE TITLE
API request logs to capture usage/scale needs

### ISSUE THREAD

**Issue by chinwallaa** [PediatricOpenTargets/OpenPedCan-api#67]
Will be useful for us to capture the API request logs, to track operational payload  to help w/ load-balancing rules for scaling

**Comment by logstar** [comment]
@blackdenc - If you have already implemented a logging system for the API prd instance, I was wondering how we could export the logs as text document for us to analyze. Let me know if there is anything that I could help with.

**Comment by devbyaccident** [comment]
We do have a cloudwatch logs group for each environment (dev, qa, and prd) in AWS under `apps-<environment>/openpedcan-api` in the account that application is running in. You should be able to access it from your role, and if not, I can work with you to assign permissions and export the logs

**Comment by logstar** [comment]
@blackdenc - Thank you. I have access to query logs for `apps-prd/openpedcan-api`.

@blackdenc @chinwallaa - Attached is an example log query result CSV file,
[logs-insights-results.csv](https://github.com/PediatricOpenTargets/OpenPedCan-api/files/8524286/logs-insights-results.csv). I think we can use such logs to track operational payload, after the API PRD instance is published.

@chinwallaa - Let me know if there is any other information in the logs that would be helpful for analyzing performance. I will see if I could query those information.
